const activities: string[] = [
  "Watch a movie together 🎬",
  "Have a cozy night with hot chocolate 🍫",
  "Try an escape room 🕵️‍♂️",
  "Play games together 🎮",
  "Cook a meal together 🍳",
  "Read books together 📚",
  "Paint and draw together 🎨",
  "Have a bubble bath together 🛁",
  "Have a wine & cheese night 🍷🧀",
  "Do a puzzle together 🧩",
  "Plan a vacation ✈️",
  "Bake cookies together 🍪",
  "Have hot pot at home 🍲",
  "Learn a new skill together 🧶",
  "Play board games 🃏",
  "Try a new workout together 🚲",
];

const places: string[] = [
  "North Van 🚢",
  "West Van 🚨",
  "Langley 🏯",
  "Coquitlam 🏢",
  "Richmond 🚈",
  "UBC 🏫",
  "Steveston 🎣",
  "Bowen Island 🏝️",
  "Victoria 🏛️",
  "White Rock 🪨",
  "The Modern Bartender 🍸",
  "Avalon Dairy 🐄",
  "Prototype Coffee ☕",
  "Grouse Montain 🏔️",
  "Bloedel Conservatory 🦋",
  "Flyover Canada 🪂",
];

const restaurants: string[] = [
  "The Italian Osteria 🇮🇹",
  "Liquids + Solids 🇺🇸",
  "Banana Leaf 🇲🇾",
  "John 3:16 🇲🇾",
  "Sho Bu Ramen 🇯🇵",
  "Phnom Pehn 🇰🇭",
  "Moltaqa 🇰🇲",
  "Baby Dhal 🇭🇹",
  "Pamir Diner 🇦🇫",
  "Vallarta's 🇲🇽",
  "Taste of Lahore 🇵🇰",
  "Robba da Matti 🇮🇹",
  "Laksa King 🇲🇾",
  "Wild Thyme 🇱🇧",
  "Jambo Grill 🇿🇦",
  "Spice of Nepal 🇳🇵",
  "Nuba 🇱🇧",
  "Vonns 🇨🇦",
  "Ha Café 🇻🇳",
  "Chao Mami 🇻🇳",
  "Bengal Grill 🇧🇩",
  "Silvestre Bistro 🇵🇪",
  "Xiaolongkan Hot Pot 🇨🇳",
  "Mirchi 🇮🇳",
  "Hawkers Delight 🇸🇬",
  "Dan Dan Noodle 🇨🇳",
  "Ruex Café 🇦🇺",
];

export { activities, places, restaurants };
